# -*- coding: utf-8 -*-
"""Vyshu_proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d16-Jma2ZpiUCoY26gM7nw6xKI035F6D
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data
data = pd.read_csv('project-data.csv', delimiter=';')

# Clean column names and strip spaces from strings in the data
data.columns = data.columns.str.strip()  # Remove extra spaces from column names
data['category'] = data['category'].str.strip()  # Remove spaces from category values

# Convert columns to numeric if possible, setting errors='coerce' to handle non-numeric values
for col in data.select_dtypes(include=['object']).columns:
    if col != 'category' and col != 'sex':  # Keep 'category' and 'sex' as strings
        data[col] = pd.to_numeric(data[col], errors='coerce')

# Check for any remaining issues
print(data.dtypes)
print(data.isnull().sum())


# Basic summary statistics
print("Summary Statistics:")
print(data.describe())

# 1. Distribution of each numerical feature
plt.figure(figsize=(16, 20))
for i, col in enumerate(data.select_dtypes(include=['float64', 'int64']).columns, 1):
    plt.subplot(4, 3, i)
    sns.histplot(data[col], kde=True, color='skyblue')
    plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

# 2. Target variable analysis
plt.figure(figsize=(8, 6))
sns.countplot(data['category'], palette='pastel')
plt.title('Category Distribution (Liver Disease)')
plt.xticks(rotation=45)
plt.show()

# 3. Distribution of 'Sex' by Disease Category
plt.figure(figsize=(8, 6))
sns.countplot(data=data, x='category', hue='sex', palette='viridis')
plt.title('Sex Distribution by Disease Category')
plt.xticks(rotation=45)
plt.show()

# 4. Correlation matrix for numerical features
plt.figure(figsize=(12, 10))
correlation_matrix = data.select_dtypes(include=['float64', 'int64']).corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

# 5. Box plots to identify outliers in liver-related variables
liver_related_cols = ['albumin', 'alkaline_phosphatase', 'alanine_aminotransferase',
                      'aspartate_aminotransferase', 'bilirubin', 'gamma_glutamyl_transferase']

plt.figure(figsize=(16, 12))
for i, col in enumerate(liver_related_cols, 1):
    plt.subplot(3, 2, i)
    sns.boxplot(data=data, x='category', y=col, palette='pastel')
    plt.title(f'Box Plot of {col} by Disease Category')
plt.tight_layout()
plt.show()